from django.urls import path

from main import views


urlpatterns = [
    path('', views.home, name='home'),
    # path("register/", views.register, name="register"),
    path('logout/', views.logout_action, name='exit'),
    path("login/", views.custom_login, name="custom_login"),
    path("materials/", views.material_list, name="material_list"),
    path("materials/add/", views.material_create, name="material_add"),
    path("materials/<int:pk>/edit/", views.material_edit, name="material_edit"),
    path("materials/<int:pk>/delete/", views.material_delete, name="material_delete"),
    path("directions/", views.direction_list, name="direction_list"),
    path("directions/add/", views.direction_create, name="direction_add"),
    path("directions/<int:pk>/edit/", views.direction_edit, name="direction_edit"),
    path("directions/<int:pk>/delete/", views.direction_delete, name="direction_delete"),
    path("locations/", views.location_list, name="location_list"),
    path("locations/add/", views.location_create, name="location_add"),
    path("locations/<int:pk>/edit/", views.location_edit, name="location_edit"),
    path("locations/<int:pk>/delete/", views.location_delete, name="location_delete"),
    path("suppliers/", views.supplier_list, name="supplier_list"),
    path("suppliers/add/", views.supplier_create, name="supplier_add"),
    path("suppliers/<int:pk>/edit/", views.supplier_edit, name="supplier_edit"),
    path("suppliers/<int:pk>/delete/", views.supplier_delete, name="supplier_delete"),
    path("incomes/", views.income_list, name="income_list"),
    path("incomes/add/", views.income_create, name="income_add"),
    path("incomes/<int:pk>/", views.income_detail, name="income_detail"),
    path("incomes/<int:pk>/delete/", views.income_delete, name="income_delete"),
    path('incomes/import/', views.import_income_excel, name='import_income_excel'),
    path("transfers/", views.transfer_list, name="transfer_list"),
    path("transfers/add/", views.transfer_create, name="transfer_add"),
    path("transfers/<int:pk>/", views.transfer_detail, name="transfer_detail"),
    path("transfers/<int:pk>/delete/", views.transfer_delete, name="transfer_delete"),
    path("writeoffs/", views.writeoff_list, name="writeoff_list"),
    path("writeoffs/add/", views.writeoff_create, name="writeoff_add"),
    path("writeoffs/<int:pk>/", views.writeoff_detail, name="writeoff_detail"),
    path("writeoffs/<int:pk>/delete/", views.writeoff_delete, name="writeoff_delete"),
    path("reports/stock/", views.report_stock, name="report_stock"),
    path("reports/movement/", views.report_movement, name="report_movement"),
    path("reports/deficit/", views.report_deficit, name="report_deficit"),
    path("reports/movement/export/", views.export_movement_excel, name="export_movement_excel"),
    path("reports/deficit/export/", views.export_deficit_excel, name="export_deficit_excel"),
]